### ISSUE TITLE
Don't use React

### ISSUE THREAD

**Issue by mcmuffin6o** [skiff-org/skiff-apps#101]
**Is your feature request related to a problem? Please describe.**
The browser page is incredibly slow and entirely non-functional in some use cases. It is so slow when I attempt to import via upload that it's effectively impossible unless I'm willing to sit in front of my computer for several hours straight uploading 5 or so emails at a time. Attempting to upload more than 15 or so emails causes hangs that don't show any loading animation but won't let me proceed even though all the emails show as "uploaded".

I worked with support to resolve this issue using a workaround, but it's emblematic of the problems that React causes.

If we're trying to compete with Gmail, we're losing -- badly.

**Describe the solution you'd like**
Use solidjs or svelte or literally anything but React.

**Describe alternatives you've considered**
I'm not a professional web developer, so I don't know if there might be a way to make React not so sluggish, memory hungry, and downright non-functional, but if there's a way to fix those things without ditching React then feel free!

Here's one lead you might pull on: https://medium.com/aimonks/revolutionizing-react-a-high-school-students-innovation-that-made-react-a-million-times-faster-3cf8ac3f4184

Technically it's a different framework, but it was designed to be similar to React.

**Additional context**
None.

**Comment by nishils** [comment]
This statement "The browser page is incredibly slow and entirely non-functional in some use cases." is not at all related to "It is so slow when I attempt to import via upload that it's effectively impossible".

The upload is a server side/networking issue that our backend team is working on improving.
