### ISSUE TITLE
Add ability to verify users' public keys

### ISSUE THREAD

**Issue by vecna13** [skiff-org/skiff-apps#103]
**Is your feature request related to a problem? Please describe.**
I can see my own verification phrase in the security settings, but as far as I can tell, there's no way to see what public keys I'm using for other users or mark their keys as verified.

**Describe the solution you'd like**
Show other users' verification phrases somewhere (probably in contacts) and allow user to verify/pin keys.

**Comment by amilich** [comment]
Coming soon - tracked here https://skiff.canny.io/feature-requests/p/encrypting-emails-sent-to-non-skiff-email-pgp

**Comment by vecna13** [comment]
The linked discussion is about sending encrypted emails to non-Skiff users via PGP. I'm talking about sending encrypted emails from a Skiff address to another Skiff address. As far as I can tell from poking around in the webmail interface, there's no way to verify that the Skiff service does not MITM the encryption. I can view my own verification phrase in security settings, but when I manage my contacts or send an email, I can't tell what public key I'm using to encrypt messages for that user.

**Comment by vecna13** [comment]
https://skiff.canny.io/feature-requests/p/verification
