### ISSUE TITLE
[MAIL - WEB] - Brave notifications broken.

### ISSUE THREAD

**Issue by C8opmBM** [skiff-org/skiff-apps#107]
I know the desktop app has a long way to go and no notifications, but at least the browser should work with notifications.
Unfortunately it wont work with brave.
Tested with chome, it does work.

Please check. Thanks!

**Comment by MX-boop** [comment]
It works on my machine.

**Comment by amilich** [comment]
Not sure about this. @C8opmBM you might need to enable "Google services" for notifications. Not sure if that's what people have done.

**Comment by C8opmBM** [comment]
On my phone it does work fine, I was refferring to the web desktop website (https://app.skiff.com/mail/inbox) which refuses to notify me no matter what.
I've deleted all cookies, disabled/re-enabled notifications (both in browser and in the skiff app), tested brave notifications with other tabs which do work, however in skiff, there's no notification message for new emails.

Very weird. I thought others can reproduce this.

**Comment by amilich** [comment]
You'll have to enable push services with Google right now, which can be done from Brave settings.
