### ISSUE TITLE
Local React Native Client

### ISSUE THREAD

**Issue by dylangerdaly** [skiff-org/skiff-apps#110]
Creating a local react native client **_with all JS and cryptography libraries included locally_** would allow users to trust Skiff's encryption, compiling the client locally would allow users to ensure the cryptography libraries are what they expect.

**Describe the solution you'd like**
Skiff to create an open-source and reproducible react native client for Linux and Windows.

This would be a big selling point over Protonmail, as everyone is aware, Protonmail and Skiff in it's current state can push malicious JS to clients that can exfil private keys, defeating all privacy preserving measures.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by swann-martin** [comment]
Actually a flutter client might be even better, you could build for windows, ios, linux and android.

**Comment by amilich** [comment]
Noting that this is actually done now. The Skiff Mail apps are built in React Native.
