### ISSUE TITLE
Repeating characters when adding email aliases in android skiff mail

### ISSUE THREAD

**Issue by razzat008** [skiff-org/skiff-apps#114]
## The Bug
I am trying to add an aliases to my email. As I start typing (eg abcdef@skiff.com) the pressed keys repeat itself creating something like (ababcababcdababcababcdef@skiff.com) . I tried changing between AOSP keyboard and OpenBoard keyboad but the issue persists. 

https://streamable.com/larypd is the video of the issue stated above. 

## Steps to reproduce
1. Launch the skiff mail app
2.  click on the profile at top right of the screen
3. click on the 'Settings' option available at near the bottom of the screen
4. choose option called 'Email aliases'
5. add new aliases and start typing

## Expected behavior
We should be able to add email aliases without the letters repeating itself as shown above. 

 - Device: [Redmi note 10 pro]
 - OS: [lineage os version 20, android 13]
 - Version [98.0]

P.S.
I could be wrong but I don't believe this is a hardware issue since all other apps are working fine while typing without any issues. So please confirm if this issue is in my device only.

**Comment by amilich** [comment]
Anyone else experiencing this

**Comment by amilich** [comment]
@razzat008 do you see this in any other text fields?

**Comment by razzat008** [comment]
> @razzat008 do you see this in any other text fields?

No i don't

**Comment by razzat008** [comment]
It apppears the issue is only seen in my device on this specific custom ROM , as I couldn't find any issue with other phones where I did same thing. So I'm closing this issue.
