### ISSUE TITLE
Allow for send-only custom domains

### ISSUE THREAD

**Issue by LeeeeT** [skiff-org/skiff-apps#115]
**Is your feature request related to a problem? Please describe.**
When adding a custom domain, Skiff requires me to create an MX record pointing to `inbound-smtp.skiff.com`. But I want my incoming emails to be proxied through Cloudflare, and Cloudflare requires a different MX record.

**Describe the solution you'd like**
Do not require MX record when adding a custom domain to support send-only domains, since MX record is only needed to receive emails, not sending them.

I tried setting up MX record as Skiff requires it, then waiting for Skiff to verify it and add my custom domain, and then changing the MX record back to Cloudflare. After DNS records were updated but not yet synced by Skiff, I was able to successfully send emails with my custom domain from Skiff and receive emails through Cloudflare which redirected them to Skiff. This worked completely fine until Skiff noticed the MX record is actually wrong (I think that's the reason). After that Skiff invalidated my custom domain and I couldn't select it when sending emails anymore.

In my understanding, the MX record is not necessary for Skiff to operate properly, and changing it from strictly "required" to "recommended" or something would solve the issue.

**Describe alternatives you've considered**
As an even more permissive solution, do not require any DNS changes at all. For example, when adding a custom domain in Yahoo, you don't need to make any changes to DNS records. Obviously, in that case you won't receive emails and your outgoing emails will fail DMARC checks, but that's a user's responsibility to setup everything correctly. You can help a user doing that by providing recommendations, but enforcing the exact DNS records match is, in my opinion, a bad idea, since there may be cases, when a user wants other yet working DNS settings.

**Additional context**
None

**Comment by amilich** [comment]
Hello! We can do this. We don't plan to include it in the consumer app because it could lead to extra confusion and domains possibly receiving mail. If you are on a paid plan, email support@skiff.org with your domain and request.

**Comment by LeeeeT** [comment]
I'm on a free plan ;)
There's no way for me to use a custom domain alongside Cloudflare, right?

**Comment by amilich** [comment]
You can use the domain in Cloudflare but would need the MX record set to Skiff

**Comment by LeeeeT** [comment]
Understood. Closing the issue then.
