### ISSUE TITLE
Quick Alias addresses don't work with Cc and Bcc

### ISSUE THREAD

**Issue by Just-a-random-person123** [skiff-org/skiff-apps#135]
**Describe the bug**
Emails sent to a Quick Alias address does not show in Skiff when sent with Cc or Bcc

**To Reproduce**
1. Compose an email (or have an email composed by somebody else)
2. Make sure one of your Quick Alias addresses is added to either Cc or Bcc
3. Send email
4. Error (says email is sent, but does not show in inbox)

**Expected behavior**
The email appears in the inbox, saying that it was sent to a Quick Alias address.

**Screenshots**
![Screenshot 2023-11-04 at 16-53-02 Inbox - jyoung12345@skiff com](https://github.com/skiff-org/skiff-apps/assets/88448050/e36c8813-6c79-4766-bcbf-22ddb5a67cc7)
![Screenshot 2023-11-04 at 16-54-55 Inbox - jyoung12345@skiff com](https://github.com/skiff-org/skiff-apps/assets/88448050/2531dcaa-ee33-4b07-a8c6-22594f069653)
![Screenshot 2023-11-04 at 16-56-19 Inbox - jyoung12345@skiff com](https://github.com/skiff-org/skiff-apps/assets/88448050/3242c012-530a-4cc7-a684-7be5e0c108be)

(notice how there is no email from quick alias address)

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2
 - Browser: Firefox
 - Version: Firefox 119
 (not tested with windows app)

**Smartphone (please complete the following information):**
(not tested on smartphone)

**Additional context**

**Comment by amilich** [comment]
Thanks for this - will look into this!

**Comment by amilich** [comment]
I think we've fixed this!
