### ISSUE TITLE
An offline view for the Calendar app

### ISSUE THREAD

**Issue by Luiszd2305** [skiff-org/skiff-apps#136]
Hi guys, I think it would be nice if in the Skiff Calendar app you could still see your stuffs when you don't have internet connection, right now it just shows you an error "Error. Failed to load" error.

**Comment by itzabhinavarya** [comment]
Hi @Luiszd2305 Sir, Kindly provide any link to produce this bug.

**Comment by amilich** [comment]
Calendar doesn't work offline today - it's a known issue

**Comment by itzabhinavarya** [comment]
Kindly assign this to me.

**Comment by amilich** [comment]
Can we move this to https://skiff.canny.io/feature-requests ?
