### ISSUE TITLE
Skiff Pass - Password Manager

### ISSUE THREAD

**Issue by Just-a-random-person123** [skiff-org/skiff-apps#138]
**Is your feature request related to a problem? Please describe.**
Lately a lot of password managers (especially LastPass) have been getting breached or issues are being found with them. The better options, like Bitwarden, lack good UI and UX so is very difficult to understand. It would be amazing if there was a Skiff password manager with Skiff's iconic clean user interface and experience

**Describe the solution you'd like**
A free, private, encrypted and reliable password manager with a clean UI and is not too hard to understand.

**Describe alternatives you've considered**
Using third party password managers - bad UI (Bitwarden), not free and/or closed-source (1Password) or has a history of data breaches (LastPass)
Using ProtonPass - closely intertwined with ProtonMail account, you _need_ to have and use a ProtonMail account to even get any use out of it.

**Additional context**

**Comment by amilich** [comment]
Hello! Thanks for the suggestion. I'd suggest checking out https://skiff.canny.io/feature-requests and adding there :)
