### ISSUE TITLE
Web application always fails after resuming session

### ISSUE THREAD

**Issue by x80486** [skiff-org/skiff-apps#139]
## Describe the Bug

Every single time I resume the operating system from hibernation, the `Skiff` application is unable to continue working without restarting with an error.

## To Reproduce

1. Install `Linux` — probably the same behavior could be observed with any operating system
1. Login into `Skiff Mail` — I always use `Firefox`, but I guess any Web browser should behave similarly
3. Hibernate or suspend the session
4. Resume the session and start using `Skiff Mail` again

## Expected Behavior

Application should be able to reconnect — I mean, even `Yahoo Mail!` does that :grimacing:

## Screenshots

![_Screenshot from 2023-11-16 19-46-38](https://github.com/skiff-org/skiff-apps/assets/34633617/d739e37d-6efc-47ab-9169-0dee8f33ccbf)

## Desktop (please complete the following information):
 - OS: `Linux`
 - Browser `Firefox`
 - Version `119.0.1 (64-bit)`

**Comment by amilich** [comment]
Have never seen this before. Chunk loading is an interesting error here.

**Comment by amilich** [comment]
Does this still happen on every load?

**Comment by x80486** [comment]
It really happens every time I resume from hibernate or suspension — which is always, because I really never shutdown 😁

Basically I resume the computer, and after the network interface takes its time to establish the connection again, if try to I use the application it really doesn't do anything because it's unable to reconnect automatically...until I see that error, and then I have to because it's the only option. I also see (those) errors in the Web browser's console.

On the other hand, I do have a `Proton` account (until `Skiff` is stable 😉 🫣) and I see how they show a notification on the top when there is no connection...and then it goes away when they establish the connection.

Probably you can steal that UX 🙌 — I've seen it in other applications as well.

**Comment by jayam04** [comment]
Can you tell me more about it because, I never faced this issue. I also tried on Firefox and it still works fine. I also tried disconnecting with network using aeroplane mode, but still no issues.

OS: `popos 22.04`
Browser: `chrome` and `firefox`

**Comment by x80486** [comment]
I'm testing this...and I don't see it fails now. Probably something changed :raised_hands:

**Comment by amilich** [comment]
That's awesome! Thank you :)
