### ISSUE TITLE
Code base does not seem to be up to date

### ISSUE THREAD

**Issue by szapp** [skiff-org/skiff-apps#140]
This repository on Github seem rather stale. `skiff-apps` has not received any commits since Oct 1st, no  non-automated-dependency-related commits since Sept 3rd, and no non-external-pull-request-merges since July 31st. However, yesterday there was an update for the iOS mail app hinting at changes that I could not pinpoint to any `skiff-org` repository. Also there has been activity in the Roadmap boards recently with new issues being moved to "In Progress" suggesting active development. The progress is great, however, I do not find anything reflected in the codebase.

I was under the impression that Skiff Mail is open-source on the client-side. Could someone clarify the statement *"Skiff Mail is open-source"* from the landing page at https://skiff.com and where I can follow the active development of Skiff Mail?

**Comment by amilich** [comment]
Just pushed massive updates. We just don't have a big eng team right now so sometimes these changes lag, and we spent a couple months rewriting the Mail app to not use NextJS. It's up to date now.
