### ISSUE TITLE
[feature]: Add mailbox filter when searching from specific mailbox in skiff mail

### ISSUE THREAD

**Issue by jayam04** [skiff-org/skiff-apps#145]
I am always frustrated when I want to search for something from Inbox or any other specific maibox as I need to add that mailbox in filter everytime.

![image](https://github.com/skiff-org/skiff-apps/assets/93824505/b257604f-3322-4fbf-bc00-08b37de177b8)
We can make Search Icon Button in top-right(pos: A in image above), to auto add mailbox in filter. Users can use Search in Sidebar(pos: B in image above) to search all mails without any initial filters applied.

**Comment by jayam04** [comment]
Hey! Should we implement this, because if yes I would like to work on it.

**Comment by amilich** [comment]
<img width="329" alt="Screenshot 2023-11-27 at 8 37 43 AM" src="https://github.com/skiff-org/skiff-apps/assets/1927690/14d5f4b0-fee2-4251-bfd6-f26c62780e6e">
Don't we already have a folder filter here?

**Comment by jayam04** [comment]
Sorry, I couldn't explain problem well. I think when using Search (Button A in main image) the mailbox filter should be automatically applied. For example using Search (again A) from Inbox should only list emails from Inbox only with whatever search query is. Similarly for searching from Archive, Trash, Quick Alias ...

**Comment by jayam04** [comment]
Currently using search, it displays emails from every mailbox whatever my current mailbox is.

**Comment by amilich** [comment]
Got it. Not sure whether we will want to do that, because we have the opposite request inside Canny - see https://skiff.canny.io/feature-requests/p/perform-search-in-all-mails-in-skiff-mobile

**Comment by jayam04** [comment]
Yeah! I wouldn't be good for mobile applications, but I think this option would be more preferable for web, as we still have Search Button in Sidebar (B in fig) to search all mailboxes. But maybe I think this conversation should be continued in canny.
