### ISSUE TITLE
Signals / Indicators for unread/new messages

### ISSUE THREAD

**Issue by x80486** [skiff-org/skiff-apps#16]
Currently there is no way to to tell if there are new messages other than getting into the folder in question. Consider implementing something like `Fastmail` to allow visual indicators in that sense:

![image](https://user-images.githubusercontent.com/34633617/195883018-72c92018-6e64-45df-8ab3-8fcebf0185cd.png)

I see those indicators only work within `Inbox` and `Spam` (for `Fastmail`, probably some other providers behave different), so I guess there are certain rules that don't apply to all folders :thinking:

**Comment by amilich** [comment]
Resolved.
