### ISSUE TITLE
You got blacklisted (new report)

### ISSUE THREAD

**Issue by ghost** [skiff-org/skiff-apps#170]
Hi!

On this https://github.com/disposable/disposable/blob/master/greylist.txt you got blocked

This is really popular filter, so please, take measures!

@amilich @jgdevelopment, @mikezzb

**Comment by amilich** [comment]
Looking into this now

**Comment by RasheedAZ** [comment]
Not in that list (yet) but there's an open issue here:
https://github.com/disposable/disposable/issues/140
