### ISSUE TITLE
Mail forwarding FROM Skiff to other email

### ISSUE THREAD

**Issue by samyak039** [skiff-org/skiff-apps#178]
**Is your feature request related to a problem? Please describe.**
Earlier, on Gmail, it used to auto-forward a filter of emails to another account. I have recently switched to Skiff, and found it frustrating that I can't do that. Now I have to manually forward those emails.

**Describe the solution you'd like**
I would like a feature to set up automatic email forwarding from my Skiff account to some other account. It should be able to handle a filter of emails, or all emails.

**Describe alternatives you've considered**
I could not find any 3rd party tool which can be used to forward emails. IF there are any, please let me know.

**Additional context**
- [Gmail Help | Automatically forward Gmail messages to another account](https://support.google.com/mail/answer/10957?hl=en)

**Comment by amilich** [comment]
Hello! Please add/upvote here - https://skiff.canny.io/feature-requests
