### ISSUE TITLE
Message headers not avaiable for e-mails sent from Skiff

### ISSUE THREAD

**Issue by vadimvera** [skiff-org/skiff-apps#179]
## Describe the Bug

The ability to display the headers from e-mails was added recently — or just today :monocle_face:

I see they are available to almost all e-mails I received, except for the ones sent by Skiff itself.

## To Reproduce

1. Open Skiff Mail
2. Open any e-mail sent by any provider and select `View headers`
3. Open any e-mail sent by Skiff — the `View headers` option is not available :grimacing:

## Expected Behavior

There shouldn't be any reason why headers from Skiff or any other provider shouldn't be available, so they should be available for any message.

## Screenshots

N/A

## Desktop

- OS: `Linux`
- Browser: `Firefox`
- Version: `121.0 (64-bit)`

## Additional Context

N/A

**Comment by amilich** [comment]
Hello! Closing this - there aren't message headers. They're not sent via SMTP and just a fixed update HTML encrypted with your account public key.
