### ISSUE TITLE
package.json missing

### ISSUE THREAD

**Issue by rltbg** [skiff-org/skiff-apps#25]
Hi there, it looks like the package.json file is missing from this repository. This file is important for tracking dependencies and running scripts for the project. Can someone please add this file to the repository? Thank you.

**Comment by xyhhx** [comment]
sup with that fr

**Comment by rrrliu** [comment]
Hey, thanks for reporting this! The root `package.json` is available at https://github.com/skiff-org/skiff-apps/blob/main/package.json
