### ISSUE TITLE
[Feature request] Support FIDO Universal 2nd Factor (U2F) WebAuth MFA/2FA

### ISSUE THREAD

**Issue by jsynowiec** [skiff-org/skiff-apps#29]
Consider adding support for FIDO Universal 2nd Factor (U2F) WebAuthn MFA/2FA. Using a hardware authentication device is more secure that TOTP, as it is not vulnerable to phishing and various forms of man-in-the-middle attacks.

**Comment by nishils** [comment]
This is completed on web. We are adding mobile support soon
