### ISSUE TITLE
Where is skiff-crypto?

### ISSUE THREAD

**Issue by xyhhx** [skiff-org/skiff-apps#36]
skiff-mail is [importing `skiff-crypto`](https://github.com/skiff-org/skiff-mail/search?q=skiff-crypto) but that's not a (public) repo in your org. Your tsconfig seems to [point to an out-of-project library](https://github.com/skiff-org/skiff-mail/blob/45217136bbae7a9d26c61437a5ab93931ca89976/skiff-mail-web/tsconfig.json#L22), too.

Your [white paper](https://skiff-org.github.io/whitepaper/Skiff_Whitepaper_2022.pdf) says "All Skiff cryptography libraries [...] are open-source and usable by other developers.", but there's nothing to be found in your org. 

What's going on with that?

**Comment by xyhhx** [comment]
Tangentially related, but, as #25 points out, you also neglected to push your package.json, so other devs can't build this project. Making it more obtuse to figure this stuff out.

**Comment by amilich** [comment]
`skiff-crypto` is https://github.com/skiff-org/typed-envelopes with some updated interfaces.

**Comment by xyhhx** [comment]
Oh okay. Is there any documentation on what the differences are?

**Comment by amilich** [comment]
Not yet, we will just rename and republish sometime soon - we are still a small team.

**Comment by xyhhx** [comment]
Alright. I'll wait for that before closing this, then.

**Comment by amilich** [comment]
Noting it's published.
