### ISSUE TITLE
pgp encryption support

### ISSUE THREAD

**Issue by Wjxfi** [skiff-org/skiff-apps#37]
all other private, open source email applications have already done this

**Comment by amilich** [comment]
Tracked here: https://skiff.canny.io/feature-requests/p/encrypting-emails-sent-to-non-skiff-email-pgp. Also, that isn't really true. Only ProtonMail relies on PGP. Other mail services may support it but are not end-to-end encrypted like Skiff is. Skiff today provides a much higher level of protection.
