### ISSUE TITLE
[Feature Request] Full Screen Split screen toggle

### ISSUE THREAD

**Issue by dicijr** [skiff-org/skiff-apps#38]
When viewing an email that needs to be full screen, the only way to make the email full screen is Appearance > Full View. I recommend a toggle somewhere or a trigger to be able to drag the column of splitview to allow larger surface area to be covered.

**Comment by rrrliu** [comment]
This can be added relatively easy as a keyboard shortcut, or an option in the command palette!

**Comment by rrrliu** [comment]
This can be added relatively easy as a keyboard shortcut, or an option in the command palette.

**Comment by amilich** [comment]
Noting merged.
