### ISSUE TITLE
[Bug] Odd HTML behavior on macos/ios app for tables.

### ISSUE THREAD

**Issue by dicijr** [skiff-org/skiff-apps#39]
<img width="683" alt="image" src="https://user-images.githubusercontent.com/42663206/219233421-357f121d-3cb9-41d6-bb5a-2aa2107b5f49.png">
<img width="808" alt="image" src="https://user-images.githubusercontent.com/42663206/219233498-48a6685b-0514-4bdc-84a6-699eaf0d7986.png">

Seems to work fine on Desktop web (not iOS web)

**Comment by amilich** [comment]
Will be fixed in an iOS mail app release in the next month.

**Comment by dicijr** [comment]
Thanks!
