### ISSUE TITLE
ReadME.md is missing - Link

### ISSUE THREAD

**Issue by BotVue** [skiff-org/skiff-apps#51]
The ReadME.md link is missing instructions on how to install and run Skiff Mail locally.

In the description it says to visit https://github.com/skiff-org/skiff-mail/blob/README.md, but when visiting the link to install and run Skiff Mail the who ReadMe.md is missing.

Could you provide us with the new link or send me the ReadMe.md?

**Comment by amilich** [comment]
Fixed
