### ISSUE TITLE
[Question] What defines the recipient for `Skiff Updates` marketing e-mail?

### ISSUE THREAD

**Issue by x80486** [skiff-org/skiff-apps#52]
I currently have three aliases. I've noticed that the `Skiff Updates` marketing e-mail is sent randomly to any of those. I wonder how is that possible, because not all addresses should be subscribed to it, otherwise I would expect the same number of e-mails as aliases.

**Comment by amilich** [comment]
Not intentional. Currently it's selecting a unique recipient but random on aliases.
