### ISSUE TITLE
Auto-sync Contacts might need a better term/language

### ISSUE THREAD

**Issue by x80486** [skiff-org/skiff-apps#55]
`Auto-sync Contacts` really doesn't convey the message. It looks like this setting is to synchronize contacts between devices or something similar...but based on the description it looks like it's the usual (infamous) auto-save setting used to save every e-mail address you reply to — or start e-mail.

![image](https://user-images.githubusercontent.com/34633617/235375194-72979f15-3ad2-436f-9f6e-1c87b932e0d1.png)

**Comment by Toine51** [comment]
Hey,
yeah, an auto-sync would be nice also with Android contacts etc !

**Comment by amilich** [comment]
I'll rename to "auto-add" right now!
