### ISSUE TITLE
Signature does not support HTML correctly

### ISSUE THREAD

**Issue by jahirfiquitiva** [skiff-org/skiff-apps#57]
### Signature in Gmail

<img width="477" alt="Shot 2023-05-16 at 10 45 43@2x" src="https://github.com/skiff-org/skiff-mail/assets/10360816/b4ac790f-d0e9-4f11-81cd-fd27befcc9c0">

### Signature in Skiff

<img width="477" alt="Shot 2023-05-16 at 10 46 35@2x" src="https://github.com/skiff-org/skiff-mail/assets/10360816/67e30b5c-2b75-466f-9f5f-6b3e4b469667">

**Comment by amilich** [comment]
We pushed a few updates for this. Let me know if better.
