### ISSUE TITLE
Web application unable to decrypt all existing mails

### ISSUE THREAD

**Issue by x80486** [skiff-org/skiff-apps#58]
Not sure what happened, but I'm currently unable to see any past e-mails. Any time I try to see any message the read panel turns completely dark and I notice I get some error messages in the browser's console.

I took a screenshot (and I removed the ID, just in case):

![image](https://github.com/skiff-org/skiff-apps/assets/34633617/2144206c-92b3-4d2c-a420-f6cdc020cb06)

New e-mails are fine.

**Comment by amilich** [comment]
Can you try clearing browser data and logging in again? Have never seen this before but I wonder if it's from having multiple accounts logged in.

**Comment by amilich** [comment]
Could you also email support@skiff.org?

**Comment by x80486** [comment]
I did a hard refresh in the tab where I have `Skiff` and the problem went away. It's a little bit weird because the assets and the manifest are the same :thinking:
