### ISSUE TITLE
Small visual bug on the website

### ISSUE THREAD

**Issue by robinscholz** [skiff-org/skiff-apps#59]
**Describe the bug**
See video

**To Reproduce**
1. Go to homepage
2. Hover on the icon bar at the bottom of page

**Expected behavior**
Sans Serif Font, clear hover zone, popover not colliding with bar.

**Screenshots**

https://github.com/skiff-org/skiff-apps/assets/8195463/326ab4f3-9ce3-4b1c-8e8e-8c5065fa39bd

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22]  114.0.5735.90

**Comment by amilich** [comment]
Definitely a bug!

**Comment by haneenmahd** [comment]
It is caused by the hover effect. As it moves upwards, it moves apart from the mouse pointer switching back to normal style. But when it reaches back, it is again hovered by the pointer resulting in moving back and forth.

**Comment by amilich** [comment]
Can't repro this now @robinscholz. May have been fixed. Tested chromium/Safari.
