### ISSUE TITLE
Skiff Crypto Readme linking to the wrong? links

### ISSUE THREAD

**Issue by bitn00b** [skiff-org/skiff-apps#60]
**Describe the bug**
The https://github.com/skiff-org/skiff-apps/tree/main/libs/skiff-crypto links both "API Documentation" and "documentation site" to https://skiff.com/crypto  - I don't know if this page will be updated or if both links point to the wrong Site 

Since there is no API Documentation at that side 😬

**Comment by haneenmahd** [comment]
Everything except the banner is up-to-date.
The link to the API docs for Skiff Crypto is https://skiff.com/skiff-crypto

**Comment by bitn00b** [comment]
Hey, yes now the URL points to the actual documentation - thank you!!  

Need to find some time to try it finally out
