### ISSUE TITLE
White Screen

### ISSUE THREAD

**Issue by Anas-1554** [skiff-org/skiff-apps#69]
**Describe the bug**

**To Reproduce**
1. Just downloaded app
2. Installed it and run it
3. Got white screen nothing else.

**Expected behavior**

**Screenshots**
![image](https://github.com/skiff-org/skiff-apps/assets/94738878/5e71a59c-99cb-455d-932e-de35b9529aac)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 
 - Browser Firefox
 - Version 10

**Comment by amilich** [comment]
Do you know if you have the Webview2 runtime on your Windows machine?

Does installing this: https://developer.microsoft.com/en-us/microsoft-edge/webview2/ fix it?

**Comment by amilich** [comment]
Closing given stale.
