### ISSUE TITLE
Mutation Error

### ISSUE THREAD

**Issue by uranium93** [skiff-org/skiff-apps#7]
I am not able to create an account with my wallet as the register mutation is failing with an unknown error.

I signed the JWT and provided access to my public key

Creating the issue as it accrues during the user onboarding process, let me know if you need more details to reproduce.

**Response**
```
{"data":{"createSrpMetamask":{"userID":null,"status":"REJECTED","jwt":null,"cacheKey":null,"email":null,"walletAddress":null,"__typename":"CreateSrpResponse"}}}```

**Comment by amilich** [comment]
Yes - what wallet are you using? What browser? Can you also email support@skiff.org and include your wallet address (or try to reproduce on a fresh wallet)?
