### ISSUE TITLE
[FEATUTE REQUEST] To be able to chose the browser when we open the links in email

### ISSUE THREAD

**Issue by acress1** [skiff-org/skiff-apps#73]
Hi, 
Today in the desktop app when there is a link in an email, we can only open it in the in-app browser, we cannot right click on the link nor select our own browser to open it. 

Would be nice to add this feature, in the settings to choose the browser! 

Thanks a lot, 
Br
Antoine

**Comment by amilich** [comment]
This is fixed in https://github.com/skiff-org/skiff-windows-app latest releases.
