### ISSUE TITLE
Add option to use different names for different alias email address

### ISSUE THREAD

**Issue by tasinone** [skiff-org/skiff-apps#79]
**Is your feature request related to a problem? Please describe.**
We can create an alias email address in skiff but we can use only one name for all the email addresses. Please make a system so that we can set different names for different alias email addresses. Although we can change the name but that's not a solution. We need a system so that we can use different names for different alias addresses.

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by amilich** [comment]
In progress! Closing - documented here. https://skiff.canny.io/feature-requests/p/different-display-name-for-each-alias
