### ISSUE TITLE
Rename does not work - Skiff Pages

### ISSUE THREAD

**Issue by ReduxFlakes** [skiff-org/skiff-apps#96]
**Describe the bug**
On Skiff Pages the option to rename a team does not work. Instead of renaming to the inputted value it stays with the old/original value.

**To Reproduce**
1. Go to any team
2. Click on "..."
3. Click on "Rename"
4. Put the desired value
5. Click on "Rename"
6. Value stays the same

**Expected behavior**
After clicking "Rename" the team name should change to the inputted value.

**Screenshots**
[Rename Bug Preview](https://imgur.com/a/2eKzaKQ)

**Additional context**
Affects mobile app, mobile web, and desktop web.

**Comment by amilich** [comment]
Should be fixed.
